name: scd_app
description: SCD Mobile Application

publish_to: 'none' #

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^2.0.0
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  mobx_codegen: ^1.1.2
  get: ^3.15.0
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  json_serializable: ^3.5.0
  json_annotation: ^3.1.0
  flutter_typeahead: ^1.8.8
  email_validator: ^1.0.5
  date_format: ^1.0.9
  connectivity: ^2.0.1
  syncfusion_flutter_calendar: ^18.3.47
  syncfusion_flutter_charts: ^18.3.47
  flutter_linkify: ^4.0.2
  url_launcher: ^5.7.10

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/stools/
    - assets/
